// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DqXl9xvigEjGXHXxmfPtglS025TZPyY',
    appId: '1:619696473015:web:026294440a909db5db5e32',
    messagingSenderId: '619696473015',
    projectId: 'project-pember',
    authDomain: 'project-pember.firebaseapp.com',
    storageBucket: 'project-pember.firebasestorage.app',
    measurementId: 'G-JQST4P3XMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWk02Rj-Tg6XsrtseKScGndd-EZkmIjNs',
    appId: '1:619696473015:android:dd0e53ed021e2e44db5e32',
    messagingSenderId: '619696473015',
    projectId: 'project-pember',
    storageBucket: 'project-pember.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALuAXxNmt7_-zw5ewdiHOqL9pOCcYntsU',
    appId: '1:619696473015:ios:2ef1467d0f4683cbdb5e32',
    messagingSenderId: '619696473015',
    projectId: 'project-pember',
    storageBucket: 'project-pember.firebasestorage.app',
    iosBundleId: 'com.example.projectPember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALuAXxNmt7_-zw5ewdiHOqL9pOCcYntsU',
    appId: '1:619696473015:ios:2ef1467d0f4683cbdb5e32',
    messagingSenderId: '619696473015',
    projectId: 'project-pember',
    storageBucket: 'project-pember.firebasestorage.app',
    iosBundleId: 'com.example.projectPember',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0DqXl9xvigEjGXHXxmfPtglS025TZPyY',
    appId: '1:619696473015:web:194c720a12d57bbfdb5e32',
    messagingSenderId: '619696473015',
    projectId: 'project-pember',
    authDomain: 'project-pember.firebaseapp.com',
    storageBucket: 'project-pember.firebasestorage.app',
    measurementId: 'G-Z6MLK727M0',
  );
}
